### ISSUE TITLE
Add links to alternate implementations in the README?

### ISSUE THREAD

**Issue by dgryski** [google/highwayhash#10]
I have ported the scalar highway hash to Go (https://github.com/dgryski/go-highway).  A quick GitHub search shows Node (https://github.com/lovell/highwayhash) and Rust (https://github.com/vks/highwayhash-rs) too.  It might be nice to mention these in the README.

**Comment by jan-wassenberg** [comment]
Sorry about the delay, I'm back. Thanks for porting to Go and making us aware of the other implementations :) All are now linked in the README.
