### ISSUE TITLE
New Nodejs bindings package

### ISSUE THREAD

**Issue by SimonAbdullah** [google/highwayhash#104]
Greetings,
I hope you are having a great day.

I've created a working NPM package to generate all variants of HighywayHash hashes (64-bit, 128-bit, and 256-bit) and published it on NPM, [highwayhash-nodejs - npm (npmjs.com)](https://www.npmjs.com/package/highwayhash-nodejs).
The provided library in your amazing documentation on GitHub is not working properly and it only supports 64-bit hashes, which is [highwayhash - npm (npmjs.com)](https://www.npmjs.com/package/highwayhash).

Advantages:
- It supports all variants; 64-bit, 128-bit, and 256-bit hashes are supported.
- It provides a native Nodejs API to handle calculated hashes; it takes Buffer as input and returns Buffer as well.
- It passes the same tests provided in Google's repo.
- Has the ability to reset the hashing key.
- It's very easy to use.

It would be very useful to the community if you consider adding it to the documentation.
Looking forward to hearing from you.

Sincerely,
Simon Abdullah

**Comment by jan-wassenberg** [comment]
Hi Simon, thanks for reaching out. Sounds great! I've updated the readme, please let me know if you'd like any other change.

**Comment by SimonAbdullah** [comment]
Perfect!
I hope that it will help. Thanks
