### ISSUE TITLE
highwayhash-wasm - WASM JS binding for the browser and nodejs

### ISSUE THREAD

**Issue by asonnleitner** [google/highwayhash#106]
Hello, as I was practising some rust with wasm-bindgen, I made this module which is a simple and useful binding of 
the rust implementation of highwayhash. It's compatible for the browser and node. I wrote some documentation
about how to use it.

You can find the repo here [highwayhash-wasm](https://github.com/asonnleitner/highwayhash-wasm) and also the [npm package](https://www.npmjs.com/package/highwayhash-wasm).

I also made an automatic ci pipeline with semantic-release, and a very please development environment. I was using esbuild for development, and building.
But in production the WASM is build from bash script because I was not able to figure out how pass RUSTFLAGS to a
node child_process. 

The WASM are optimized for size and embedded as base64 in the module source.

I was also planning to add some helper function for the hasher key generation. So it would be more user friendly.
Maybe I'll add it in the future.

**Comment by jan-wassenberg** [comment]
Hi @asonnleitner , nice! Would you like me to add it to the readme?

**Comment by asonnleitner** [comment]
Hi @jan-wassenberg, sure! It would be a pleasure!

**Comment by jan-wassenberg** [comment]
Done :)
