### ISSUE TITLE
Alignment attributes are in the wrong place for arrays

### ISSUE THREAD

**Issue by joemmett** [google/highwayhash#109]
Some array declarations use `HH_ALIGNAS` after the array bound in some files. This is invalid C++ when `HH_ALIGNAS` expands to the standard C++ `alignas` specifier. Moving `HH_ALIGNAS` to before the type makes it conforming and should still work with the gcc attribute, and some declarations already use this form.

Clang will diagnose these when `alignas` is used, it only works now because it looks like the GCC attribute is still used for clang builds because it defines an old __GNUC__ value. MSVC will diagnose these in some places when using /permissive-.

**Comment by jan-wassenberg** [comment]
Thanks @joemmett for pointing this out. I've made this change locally and it will take some time to land, likely next week.
