### ISSUE TITLE
Question: When the README says "an expected 2^32 guesses of m per the birthday paradox", does it refers to 128 and 256-bits versions too?

### ISSUE THREAD

**Issue by alpominth** [google/highwayhash#118]
`"By contrast, 'strong' hashes such as SipHash or HighwayHash require infeasible attacker effort to find a hash collision (an expected 2^32 guesses of m per the birthday paradox) or recover the seed (2^63 requests). These security claims assume the seed is secret."`

/\ Does this refers to 128 and 256-bits versions too?

**Comment by jan-wassenberg** [comment]
Hi, this section discusses hash tables, for which an (up to) 64-bit hash function would be used, so this section refers only to such functions.

We believe that the 128 and 256-bit versions of HighwayHash are much stronger. Our security analysis in the [paper](https://arxiv.org/pdf/1612.06257.pdf) discusses some possible attacks and sees a 1 in 2^64 upper bound for a differential, but this is not necessarily tight. The probability of a successful attack might actually be lower, but we have not been able to demonstrate this.
