### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by vks** [google/highwayhash#12]
The gunit dependency breaks the build for me:

```diff
    deps = [
        ":sip_hash",
        "//testing/base/public:gunit_main_no_google3",
    ],
```

I'm not sure how to get it.

**Comment by vks** [comment]
A workaround is not compiling the test:

```
bazel build -c opt --copt=-mavx2 --copt=-fPIC -- :all -:sip_hash_test
```

**Comment by jan-wassenberg** [comment]
I'm sorry the test is complicating things. Looks difficult to keep the internal and external version in sync there.
FYI the test infrastructure is also open-sourced (https://github.com/google/googletest), but I've not tried integrating the open-source version.

Not ideal, but your workaround is fine. FYI building only the main app is possible with simpler syntax:
bazel build -c opt --copt=-mavx2 --copt=-fPIC -- :sip_hash_main

You can also use make if that's easier. Does that solve the issue for you?

**Comment by vks** [comment]
For my purpose I don't need the executable, only the libraries for static linking. So I'm actually using `-:sip_hash_main` as well.

I think it is fine to depend on googletest, but it should probably be mentioned in the README where to get it and how to compile without it by not building the tests.

**Comment by jan-wassenberg** [comment]
Ah, I understand. Thanks, I've mentioned your workaround and the dependency in the README.
