### ISSUE TITLE
 InstructionSets::Run<HighwayHash>

### ISSUE THREAD

**Issue by hys-2233** [google/highwayhash#124]
Hi,
I wanted to try bazel to build the example in  InstructionSets::Run<HighwayHash>(key, in, 8, &result); that you have in your README. However, I cannot make it work as it requires the definition of the operator ():
undefined reference to 
`bazel-out/k8-fastbuild/bin/highwayhash_test/_objs/highwayhash_test/highwayhash_test.pic.o:highwayhash_test.cc:function unsigned int highwayhash::InstructionSets::Run<highwayhash::HighwayHash, unsigned long const (&) [4], char const*, unsigned long, unsigned long*>(unsigned long const (&) [4], char const*&&, unsigned long&&, unsigned long*&&): error: undefined reference to 'highwayhash::InstructionSets::Supported()'
bazel-out/k8-fastbuild/bin/highwayhash_test/_objs/highwayhash_test/highwayhash_test.pic.o:highwayhash_test.cc:function unsigned int highwayhash::InstructionSets::Run<highwayhash::HighwayHash, unsigned long const (&) [4], char const*, unsigned long, unsigned long*>(unsigned long const (&) [4], char const*&&, unsigned long&&, unsigned long*&&): error: undefined reference to 'highwayhash::HighwayHash<4u>::operator()(unsigned long const (&) [4], char const*, unsigned long, unsigned long*) const'
bazel-out/k8-fastbuild/bin/highwayhash_test/_objs/highwayhash_test/highwayhash_test.pic.o:highwayhash_test.cc:function unsigned int highwayhash::InstructionSets::Run<highwayhash::HighwayHash, unsigned long const (&) [4], char const*, unsigned long, unsigned long*>(unsigned long const (&) [4], char const*&&, unsigned long&&, unsigned long*&&): error: undefined reference to 'highwayhash::HighwayHash<2u>::operator()(unsigned long const (&) [4], char const*, unsigned long, unsigned long*) const'
bazel-out/k8-fastbuild/bin/highwayhash_test/_objs/highwayhash_test/highwayhash_test.pic.o:highwayhash_test.cc:function unsigned int highwayhash::InstructionSets::Run<highwayhash::HighwayHash, unsigned long const (&) [4], char const*, unsigned long, unsigned long*>(unsigned long const (&) [4], char const*&&, unsigned long&&, unsigned long*&&): error: undefined reference to 'highwayhash::HighwayHash<1u>::operator()(unsigned long const (&) [4], char const*, unsigned long, unsigned long*) const'` Is there a way to use theInstructionSets::Run` interface with your current repository?
Many thanks in advance!

**Comment by jan-wassenberg** [comment]
Hi, it looks like some of the source files including instruction_sets.cc might not be in your BUILD file?

Maybe a better alternative would be to instead use https://github.com/johnplatts/simdhwyhash - this is a more modern implementation using Highway, whose compilation and dynamic dispatch mechanism is simpler and easier to use that what we have here (its predecessor).

**Comment by hys-2233** [comment]
Thank you for your explanation. I'll give it a try.
