### ISSUE TITLE
Missing include of <cmath> in nanobenchmark.h

### ISSUE THREAD

**Issue by lorenzhs** [google/highwayhash#18]
The overload `std::abs(float arg)` is declared in header `<cmath>`, which is not currently included in [nanobenchmark.h](https://github.com/google/highwayhash/blob/master/highwayhash/nanobenchmark.h). This causes the build to fail on my system (Debian unstable, g++ 6.1).

**Comment by jan-wassenberg** [comment]
Thanks for reporting, fixed :)
