### ISSUE TITLE
Publish SMHahser binding and results

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [google/highwayhash#20]
AFAIR, You have mentioned in encode.ru forum that HighwayHash passed SMHasher tests with better results than any other hashes. Can you please publish your results and SMHasher integratyion code?

I'm excited since it seems that even SHA1/MD5 doesn't provide results different than MurMur3/Spooky2/xxHash, i.e. all these hashes are indistinguishable from ideal hash as far as you meaure only with SMHasher.

**Comment by jan-wassenberg** [comment]
Hi Bulat, thanks, we're working on it :) The ThreadPool dependency is already resolved, we're still thinking about how/where to release the revised smhasher.

**Comment by Bulat-Ziganshin** [comment]
Dup of #17
