### ISSUE TITLE
Cannot build with bazel

### ISSUE THREAD

**Issue by vks** [google/highwayhash#25]
I'm getting this error when trying to compile highwayhash with bazel:

```
ERROR: highwayhash/BUILD:39:1: no such package 'base': BUILD file not found on package path and referenced by '//:vector_test'.
```

Maybe `base` is something internal at Google?

**Comment by jan-wassenberg** [comment]
Hi Vinzent, that's correct, the real problem is the lack of "manual" tag. I've added it, so that test target should no longer be built unless manually specified. Thanks for reporting, and please let me know if that doesn't solve it for you :)

**Comment by vks** [comment]
Thanks for the fix, now I'm getting this error:

```
ERROR: highwayhash/BUILD:131:16: in includes attribute of cc_library rule //:data_parallel: '.' resolves to the workspace root, which would allow this rule and all of its transitive dependents to include any file in your workspace. Please include only what you need.
```

**Comment by jan-wassenberg** [comment]
Thanks for bringing this up. Looks like Bazel has changed its behavior, this was previously allowed.
Coincidentally we're changing the file structure to speed up builds, which will also remove the problem Bazel complains about.

Some questions for you: would it be troublesome if we changed the paths to ```#include third_party/highwayhash/..."```?
Also, do you need the Bazel build capability, or is the Makefile sufficient?

I'm trying to keep the github/internal versions in sync without conversions in either direction, but it is getting a bit difficult :)

**Comment by vks** [comment]
About your questions:
* I don't think changing the includes would be a problem.
* I'm linking statically against bazel, if I understand correctly this is currently not supported by the makefile. In fact, I would prefer to use make for the Rust bindings, because it is a much more lightweight/common dependency. So for me it would be fine to only have the makefile, if it supported static linking.

Maybe the best path forward is to use the Bazel file only internally at Google and maintain only the Makefile for the public version of highwayhash?

**Comment by vks** [comment]
With #26 I no longer need Bazel for the Rust bindings.

**Comment by jan-wassenberg** [comment]
Thank you for the Makefile update :) The include path changes and a few other fixes are coming soon.
