### ISSUE TITLE
Add SipHash13 variant cause it is already secure enough for most usages.

### ISSUE THREAD

**Issue by funny-falcon** [google/highwayhash#30]
SipHash13 is already secure for use in hash table implementations, and most of other usages too.

Rust language already had switched to SipHash13. Discussion:
https://github.com/rust-lang/rust/issues/29754
Comment from Jean-Phillipe Aumasson:
https://github.com/rust-lang/rust/issues/29754#issuecomment-156073946

**Comment by jan-wassenberg** [comment]
Hi, sounds useful, thanks for suggesting 👍 Would you be able to make a PR? I'd be happy to merge.

(If so: easiest to make SipHashState a template and replace the hardcoded <2>, <4> with params; let's also add a C wrapper to c_bindings.h.)

**Comment by jan-wassenberg** [comment]
Made minor additional changes: clang-format, rename to match coding convention, update readme.
Thanks for the suggestion and patch!
