### ISSUE TITLE
Hash values mismatch on big endian Vs little endian

### ISSUE THREAD

**Issue by shahidhs-ibm** [google/highwayhash#35]
While working on big endian machine, we observed that the hash results are coming different than what we got on little endian machine. Though this is expected behavior, by any chance is there any possibility to make the hash values consistent across big and little endian architectures?

A 64 bit byte swap in the "Update" method in "highwayhash/sip_hash.h", made the hash results consistent for us.

**Comment by jan-wassenberg** [comment]
Thanks for pointing this out. I'd be happy to add bswap. Proposal:

    #if ARCH_X64
    #define HH_LITTLE_ENDIAN 1
    #define HH_BIG_ENDIAN 0
    #else
    #define HH_LITTLE_ENDIAN 0
    #define HH_BIG_ENDIAN 1
    #endif
    
      HH_INLINE void Update(const char* bytes) {
        uint64 packet;
        memcpy(&packet, bytes, sizeof(packet));
    #if HH_BIG_ENDIAN
        packet = HH_BSWAP64(packet);
    #endif

Do you have any concerns or suggestions about this approach?

**Comment by shahidhs-ibm** [comment]
Thanks for taking the request into consideration. The changes looks good to me.

**Comment by jan-wassenberg** [comment]
Thanks for reviewing it! I'm out of the office this week and will push the change next week.

**Comment by jan-wassenberg** [comment]
Happy new year! Unfortunately it will be another couple of days until we get this pushed.

**Comment by jan-wassenberg** [comment]
Done :)

**Comment by shahidhs-ibm** [comment]
@jan-wassenberg Thanks a lot :)
