### ISSUE TITLE
Couldn't figure out how to install on a Raspberry Pi

### ISSUE THREAD

**Issue by matteomonti** [google/highwayhash#37]
I am pretty sure this is a dumb question, hope you'll bear with me.
I have a clean install of Raspbian on a Raspberry Pi 3, just with git and the few tools needed to compile. I naively followed the very brief Build instructions on the README and attempted a `make`. 

    g++: error: unrecognized command line option ‘-mavx2’
    <builtin>: recipe for target 'highwayhash/os_specific.o' failed
    make: *** [highwayhash/os_specific.o] Error 1

Am I to assume that the Raspberry Pi is not a supported platform for Highway? Otherwise, could someone point me to an easily followable set of instructions to get Highway on my Raspberry and compute a 256 bit hash of something? I easily get lost.

Thank you so much,
sorry for the not-really-inspired question.

**Comment by Bulat-Ziganshin** [comment]
the hash has 3 versions - avx2, sse4 and general cpu, you need the last one. that said, i wonder why you need 256-bit non-cryptographic hash?

**Comment by jan-wassenberg** [comment]
Yes, ScalarHighwayTreeHash() from scalar_highway_tree_hash.h in the current code - we're moving to a template+runtime CPUID dispatcher soon.

I'd also be curious what your intended use case is. HighwayHash is only fast if some kind of SIMD is available. It's not yet ported to ARM's NEON.

**Comment by jan-wassenberg** [comment]
FYI the portable implementation has been renamed to HighwayHashT<TargetPortable, HHResult256>.

The Makefile now contains a comment at the -mavx2 - you can remove that and disable the hh_avx2.o and hh_sse41.o makefile targets.

**Comment by jan-wassenberg** [comment]
FYI the makefile is updated again, you can define the HH_AARCH64 variable to 1 and it should skip x86-specific things. Please feel free to reopen this issue if needed.
