### ISSUE TITLE
Makefile ignores CXXFLAGS

### ISSUE THREAD

**Issue by vks** [google/highwayhash#38]
Running commands like `CXXFLAGS=-fPIC make libhighwayhash.a` does not seem to work, it looks like the environment variable is ignored. (I think it did work before the recent changes.)

(I relied on this functionality for the Rust bindings (because Rust requires `-fPIC` even for static linking). A possible workaround is to patch the makefile, but it would be cleaner to just pass the additional flag via environment variables.)

**Comment by jan-wassenberg** [comment]
We could change the ```CXXFLAGS :=``` line into

    HH_ARCH := -mavx2
    HH_CXXFLAGS := 
    CXXFLAGS = -I../../ -std=c++11 -Wall -O3 $(HH_ARCH) $(HH_CXXFLAGS)
Then you could invoke ````make HH_CXXFLAGS=-fPIC```.

Would that help?

**Comment by vks** [comment]
Yes, that would work!

(Not sure why the old way does not work anymore though.)

**Comment by jan-wassenberg** [comment]
Yes, that's surprising. But thanks for reviewing, I'll push this change tomorrow.

**Comment by jan-wassenberg** [comment]
Done (c6c4810). Please feel free to reopen if you have other change suggestions!

**Comment by vks** [comment]
Thanks, I updated my Rust bindings.

**Comment by jan-wassenberg** [comment]
Hi, FYI we've fixed the underlying issue; the updated Makefile now just appends to CXXFLAGS, so we no longer need the HH_ARCH workaround. Sorry to change it again; my knowledge of Makefiles is increasing from a fairly low baseline :)
