### ISSUE TITLE
how to build a generic highwayhash library for different machines?

### ISSUE THREAD

**Issue by CDLuminate** [google/highwayhash#42]
Is setting `HH_ARCH=` (empty) enough for that purpose?

**Comment by jan-wassenberg** [comment]
Hi, the existing code should already be able to compile a library for several x86 targets (AVX2/SSE4). Have you seen the HighwayHash64_Dispatcher interface in c_bindings and its highwayhash_target.cc implementation? Also, the hh_portable implementation should work on any little-endian machine (TODO: byte-swapping); we verify it on ARM and PPC, but with a newer version of the code.

This change will switch template arguments from struct TargetAVX2 to integral constants, and ensure safety (avoid ODR violations) when compiling with different flags for different machines.

Does that answer your question?

One remaining issue before pushing: we're not yet disabling the hh_avx2 etc targets in the Makefile on non-x86. Would appreciate some input from anyone who has done this before.

**Comment by jan-wassenberg** [comment]
Just pushed the above mentioned change, it's huge. Rather than HH_ARCH, we now have make variables HH_X64, HH_POWER etc, which resolves the previous question of how to disable some make targets.
