### ISSUE TITLE
compilation with makefile does not work

### ISSUE THREAD

**Issue by vks** [google/highwayhash#43]
This patch fixes some include problems:

```diff
diff --git a/Makefile b/Makefile
index de631a3..8f8fd82 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@
 # We assume X64 unless HH_POWER or HH_AARCH64 are defined.
 
-override CPPFLAGS += -I../..
+override CPPFLAGS += -I.
 override CXXFLAGS +=-std=c++11 -Wall -O3
 
 SIP_OBJS := $(addprefix obj/, \
```

However, there is still another problem:

```
make: ./test_exports.sh: Command not found
```

Maybe this file was not committed by accident?

**Comment by jan-wassenberg** [comment]
Thanks for pointing this out!
Sorry about the include path breakage, we had a regex from ../../ to . that no longer triggered after changing the path to "../..".
I also didn't add test_exports.sh to the MOE sync config; fixed and pushed now :)

**Comment by vks** [comment]
Great, thanks for the fix!
