### ISSUE TITLE
building the static library with -fPIC fails

### ISSUE THREAD

**Issue by vks** [google/highwayhash#45]
```
> CXXFLAGS=-fPIC make lib/libhighwayhash.a
[...]
./test_exports.sh lib/libhighwayhash.a
DW.ref.__gxx_personality_v0
The above-mentioned symbols are duplicates
FAIL
```

The newly added check for duplicated symbols fails.

**Comment by jan-wassenberg** [comment]
I'm sorry we keep running into potholes here :)
Am able to reproduce with our gcc 4.8, thanks for reporting. We'll look into a fix on Fri.
In the mean time, you can disable this Make rule (just a safety check, and looks like a false alarm).

**Comment by jan-wassenberg** [comment]
We're still thinking about the best fix. The most promising candidate so far is to move away from detecting duplicates (always prone to false-positives) towards ensuring e.g. SSE4 files only export symbols with "SSE4" in their name. Will be a few more days.

**Comment by jan-wassenberg** [comment]
FYI the test is currently disabled.

**Comment by CDLuminate** [comment]
Note, this PR https://github.com/google/highwayhash/pull/55 will enable `-fPIC` by default. And it seems to be working for both shared object and static one.

**Comment by jan-wassenberg** [comment]
Yes, noted. Our test here was overzealous and eventually we'll change it as mentioned above.
