### ISSUE TITLE
Recent addition of endianess fails to compile on MSVC

### ISSUE THREAD

**Issue by lovell** [google/highwayhash#46]
Hello, it looks like this started with commit e2098bc.

> fatal error C1083: Cannot open include file: 'sys/param.h': No such file or directory (compiling source file highwayhash\highwayhash_target.cc

It's tripping up due to MSVC's non-availability of `<sys/param.h>` in [endianess.h](https://github.com/google/highwayhash/blob/master/highwayhash/endianess.h#L60).

Not sure what the best way to workaround this is but https://github.com/blizzard4591/cmake-portable-endian provides a possible start.

**Comment by jan-wassenberg** [comment]
Oops, sorry - we don't build often with MSVC. Will fix momentarily by hard-coding to little endian on Windows (can override by defining BIG_ENDIAN=2, LITTLE_ENDIAN=1, BYTE_ORDER=2 in the project).
Thanks for reporting!

**Comment by lovell** [comment]
Thanks for the quick fix.

MSVC is also stumbling over the addition of `__builtin_memcpy` in [load3.h](https://github.com/google/highwayhash/blob/e2098bc92a8540e133b11207ed1f1abfca57724c/highwayhash/load3.h#L60) as part of the same commit.

> error C3861: '__builtin_memcpy': identifier not found (compiling source file highwayhash\highwayhash_target.cc)

**Comment by jan-wassenberg** [comment]
Added a Copy function wrapper to fix this - thanks for reporting!

**Comment by lovell** [comment]
[Confirmed working](https://ci.appveyor.com/project/lovell/highwayhash/build/17) with MSVC, thank you very much.
