### ISSUE TITLE
Escape internal state=zero

### ISSUE THREAD

**Issue by jan-wassenberg** [google/highwayhash#5]
In HighwayTreeHash, keys are not attacker-controlled, but a potential worst-case involves key = init0/1. As a result, either v0 or v1 can be zero. Suppose it is v1 and an attacker chooses all-zero input packets. Then any packets with (length mod 256 = 0) collide.

If instead v0 = 0 after init and the key is known, attackers can choose the first input such that v1 becomes and remains 0. Obviously this attack requires the secret key to be known, but we would like the hash to be viable in that scenario as well (to serve as a fingerprint).

We are considering several possible workarounds:
* preventing v1=0 after init by checking the result of key ^ init1
* mixing non-zero bits into v1 during every round
* some other way of escaping v0 = v1 = 0

**Comment by waywardgeek** [comment]
Anything we do will slow hashing down, but I found that doing pre-processing on the packet can be done in parallel with the main hashing loop, and slows it down less than other options:

    const uint64_t maskVal = 0x7171717171717171ULL;
    const V4x64U mask(maskVal, maskVal, maskVal, maskVal);
    const V4x64U maskInv(~maskVal, ~maskVal, ~maskVal, ~maskVal);
    v0 ^= packet & mask;
    v1 ^= packet & maskInv;

On my Haswell laptop, this slows it down from 0.37 c/b (9.42 GB/s) to 0.38 c/b (9.24 GB/s).

Alternatively, we could leave HighwayHash as a SipHash-like variant that assumes the secret key is secret, generating 64-bit hashes.  This is perfect for MACs.  I am personally leaning towards this, since I think we will need more rounds and more mixing on a larger state to build a cryptographically secure geneeral purpose hash function.  My current Update function for such use looks like:

    const uint64_t maskVal = 0x00ff00ff00ff00ffull;
    const V4x64U mask(maskVal, maskVal, maskVal, maskVal);
    const V4x64U maskInv(~maskVal, ~maskVal, ~maskVal, ~maskVal);

    V4x64U mul0(_mm256_mul_epu32(v0, Permute(v2)));
    V4x64U mul1(_mm256_mul_epu32(v1, Permute(v3)));
    V4x64U mul2(_mm256_mul_epu32(v0 >> 32, v2));
    V4x64U mul3(_mm256_mul_epu32(v1 >> 32, v3));
    
    v0 ^= packet1 & mask;
    v1 ^= packet1 & maskInv;
    v2 ^= packet2 & mask;
    v3 ^= packet2 & maskInv;
    v0 ^= ZipperMerge(mul1);
    v1 ^= ZipperMerge(mul0);
    v2 ^= ZipperMerge(mul3);
    v3 ^= ZipperMerge(mul2);

**Comment by jan-wassenberg** [comment]
Nice, looks like that prevents the second attack (init v0 to 0, force v1 to 0 using first input packet), but we need to swap mask and maskInv:
`    const V4x64U mask(0x7171717171717171ULL);
    v0 += AndNot(mask, packet);
    v1 += mask & packet;
    v0 |= V4x64U(0x0000000070000001ULL);`

Alternatively, we can add the previous state at the end of Update:
`    v0 += ZipperMerge(mul0) + prev_v1;
    v1 += mul1 + prev_v0;`
Not yet clear which is better.

We can also easily address the collisions from all-zero inputs of different lengths by adding `Update(size)` at the beginning of `Finalize()`.

**Comment by waywardgeek** [comment]
How about this function:

    const V4x64U mask(0x5555555555555555ull);
    v0 ^= AndNot(mask, packet);
    v1 ^= mask & packet;
    V4x64U mul0(_mm256_mul_epu32(v0, v0 >> 32));
    V4x64U mul1(_mm256_mul_epu32(v1, v1 >> 32));

    v0 ^= ZipperMerge(mul1);
    v1 ^= mul0;

On my laptop, this runs in 0.35 c/b on 1KiB, compared to 0.37 for the original, so it is slightly faster.  Also, since easy step other than XORing in the packet is reversible, we know do not lose entropy.  This is why I changed mul0 to only use v0, and mul1 to only use v1.  Since it is now reversible, we no longer need the OR operation.

**Comment by waywardgeek** [comment]
A slightly faster version:

    const V4x64U mask(0x5555555555555555ull);
    V4x64U mul0(_mm256_mul_epu32(v0, v0 >> 32));
    V4x64U mul1(_mm256_mul_epu32(v1, v1 >> 32));
    v0 ^= mask & packet;
    v1 ^= AndNot(mask, packet);
    v0 ^= ZipperMerge(mul1);
    v1 ^= mul0;

This runs in 0.32 c/b on my laptop.  I prefer the ^= over +=.  When absorbing the packets, it lets us know exactly which bits the attacker can control (even bits in v0, odd bits in v1).  The ^= with multiplication results should defeat algebraic attacks.

**Comment by jan-wassenberg** [comment]
It's a tricky balance between distribution, speed and predictability. Unfortunately this latest proposal has insufficient avalanching (> 1.5% bias). I think we do need to OR in bits before multiplying, and the carry ripples from + instead of ^ also help in mixing.
Your previous mask 0x71..71 mask seems to work well.

**Comment by waywardgeek** [comment]
On Thu, Mar 10, 2016 at 2:20 AM, Jan Wassenberg <notifications@github.com>
wrote:

> It's a tricky balance between distribution, speed and predictability.
> Unfortunately this latest proposal has insufficient avalanching (> 1.5%
> bias). I think we do need to OR in bits before multiplying, and the carry
> ripples from + instead of ^ also help in mixing.
> Your previous mask 0x71..71 mask seems to work well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/highwayhash/issues/5#issuecomment-194776303>.
>
Can you explain how avalancing bias is computed?  Thanks.

**Comment by jan-wassenberg** [comment]
Sure :) That's the "Avalanche Tests" section in smhasher.cc (the RunAllTests function we talked about). I recommend running that after every change that changes the hash algorithm.

**Comment by waywardgeek** [comment]
I played around with a number of variations.  This one runs in 0.35 c/b, which is faster than the original at 0.37 c/b on my laptop, and it passes avalanche tests.  It has some other properties I like as well:

    V4x64U mask(0x5555555555555555ull);
    v0 += mask & packet;
    v1 += AndNot(mask, packet);const
    V4x64U mul0(_mm256_mul_epu32(v0, v0 >> 32));
    V4x64U mul1(_mm256_mul_epu32(v1, v1 >> 32));
    v0 += ZipperMerge(v1);
    v1 += ZipperMerge(v0);
    v0 ^= mul1;
    v1 ^= mul0;

Note that if the input is all 0's, it reverts to a hash function that resembles SipHash, with an XOR, ADD, and mixing step.  The original function is missing the XOR step, which I feel is needed for nonlinearity.

**Comment by jan-wassenberg** [comment]
Thumbs up, that does well on avalanche and speed is also good.
Also looks to solve the zero-state problem - even if either state is zero, nonzero bits would be mixed in during the round. I like it, but let's wait for jyrki to comment.

**Comment by waywardgeek** [comment]
I now believe that we should not try to modify HighwayHash to be suitable for generating fingerprints.  Instead, it should remain optimized for MAC generation.  If we decide to focus only on MACs, I think this issue can be closed.  The original HighwayHash function does not have a problem escaping 0 when the key is not known to the attacker.

Like SipHash, HighwayHash in its current form should not be used to generate unique fingerprints.  To be secure, we would have to increase the output from 64 bits to 256, mix between lanes during hashing, improve resistance to differential attacks (more than any of my modified versions), which may mean adding multiple rounds of Update per packet, and increase the number of rounds in Finalize.  Such changes would most likely result in a very fast generic cryptographic hash function, but it would not be as fast as HighwayHash for generating MACs, especially for small messages.

My most recent version of the Update function does not try to be secure against attackers who know the secret key.  The only point of the following Update function is improving resistance to differential attacks.  I found a minor differential attack against my function above.  I believe this new function below is resistant to differential attacks at the 64-bit level, but it is not suitable for generating longer hashes:

    v1 += packet;
    v1 += mul0;
    mul0 ^= V4x64U(_mm256_mul_epu32(v0, v1 >> 32));
    v0 += mul1;
    mul1 ^= V4x64U(_mm256_mul_epu32(v1, v0 >> 32));
    v0 += ZipperMerge(v1);
    v1 += ZipperMerge(v0);

**Comment by jan-wassenberg** [comment]
We've tested the above Update (plus modifications to Init and Finalize) with the smhasher bias metric and the additional histogram/state visualizations and it looks good! I've pushed an update and we can consider this issue solved. Thank you for suggesting this modification!
