### ISSUE TITLE
install flags are wrong

### ISSUE THREAD

**Issue by yurivict** [google/highwayhash#58]
1. headers should be installed read-only: 0444
2. libhighwayhash.a should also be read-only: 0444
3. libhighwayhash.so should be 0555

**Comment by jan-wassenberg** [comment]
Hi +yurivict, thanks for reaching out. I will attempt to fix this soon :) BTW we just added a PPC port and froze HHResult64.

**Comment by jan-wassenberg** [comment]
@yurivict Thanks again for reporting this. I updated the Makefile in eeea4463df1639c7ce271a1d0fdfa8ae5e81a49f, which also freezes the 128 and 256 bit variants.
