### ISSUE TITLE
Provide Python bindings

### ISSUE THREAD

**Issue by pombredanne** [google/highwayhash#61]
It would be awesome if there was a Python binding for this. You do not happen to have one stashed somewhere by chance?
Thanks!

**Comment by jan-wassenberg** [comment]
Hi Philippe, we don't yet have Python bindings and I don't have much experience with them, but would be happy to add them if you can send a patch :)

**Comment by pombredanne** [comment]
@jan-wassenberg Thank you for the swift reply. I will try to give it a shot.... I especially appreciate the fact that this hash is "portable" e.g. as stated the 64 and 128 versions output will not change if I run the same code on the same input on two different machines (at least two AMD or Intel architecture CPUs) which is really awesome and important IMHO

Unrelated: any plan to publish some smhasher results?

**Comment by jan-wassenberg** [comment]
Sounds good! Thanks, yes, unchanging fingerprint functions are very useful indeed.

smhasher results are posted here: https://github.com/google/highwayhash/issues/17

**Comment by jan-wassenberg** [comment]
FYI the 128 and 256 bit variants are now frozen (after increasing the number of finalization rounds to 6 and 10).

**Comment by jan-wassenberg** [comment]
Hey Phil, happy to see your binding, looks good 👍 
I've added mention of it to the readme, please let me know if you'd like any changes.

**Comment by pombredanne** [comment]
@kpdemetriou this is very nice. :bowing_man:  Thank you! I wished it would support Python 2 but that's not critical..
I think this ticket is good to close now.

**Comment by pombredanne** [comment]
For reference the README commit is https://github.com/google/highwayhash/commit/9099074416ebc926c9e5e6f5143db92ebd9b4c03
