### ISSUE TITLE
Different hashes for identical input....

### ISSUE THREAD

**Issue by electroglyph** [google/highwayhash#68]
I'm using HighwayHash to hash tons of strings.  While reviewing some results I came across something odd: HH appeared to give a different hash for the same input.  Same key, same state, other inputs work normally.

The string that triggered this: "GCC: (GNU) 4.8.3" (quotes not included).  My test case is in C, with the previous string zero-padded to 32 bytes.  If I hash it 16 times I get 16 different hashes.  I've tried different keys, different architectures, this is also the only string that exhibits this behavior so far.  Strangely enough it doesn't seem to matter if the above string is hashed directly, or if it's zero-padded to 32 bytes.

Can anyone repeat this?  Am I or my machine crazy?

**Comment by dgryski** [comment]
Can you show us your source code?

**Comment by electroglyph** [comment]
I'm retarded.

**Comment by jan-wassenberg** [comment]
@electroglyph  No worries, mistakes happen :) Thanks for letting us know the problem is resolved!
