### ISSUE TITLE
HighwayHash for the CPU on which we're currently running

### ISSUE THREAD

**Issue by dimstamat** [google/highwayhash#73]
Hi,

I wanted to try the `InstructionSets::Run<HighwayHash>(key, in, 8, &result);` that you have in your README. However, I cannot make it work as it requires the definition of the operator ():
`undefined reference to `highwayhash::HighwayHash<1u>::operator()(unsigned long const (&) [4], char const*, unsigned long, unsigned long (*) [2]) const'`, which is in the highwayhash_target.cc file. I do not see any highwayhash_target.o file produced in obj.
The highwayhash/highwayhash_test.cc does not use the `InstructionSets::Run<HighwayHash>`, but the `InstructionSets::RunAll<HighwayHashTest>`, (`PRINT_RESULTS` is 0). If I set `PRINT_RESULTS` to 1 it fails to build for the same error.
Is there a way to use the `InstructionSets::Run<HighwayHash>` interface with your current repository?
Many thanks in advance!

**Comment by jan-wassenberg** [comment]
Thank you for reporting this. I see that the Makefile does not add `HIGHWAYHASH_OBJS` to `HIGHWAYHASH_TEST_OBJS`. Will be fixed shortly :+1:

**Comment by jan-wassenberg** [comment]
Please feel free to reopen if you still see an issue.
