### ISSUE TITLE
Highwayhash on PPC

### ISSUE THREAD

**Issue by vaibhavsood** [google/highwayhash#74]
Hi, 

I am looking at the PPC implementation https://github.com/google/highwayhash/blob/master/highwayhash/hh_vsx.h

My query is if this implementation can be optimized further by completely implementing in assembly?

There is a minio implementation of Highwayhash for Intel all in assembly https://github.com/minio/highwayhash/blob/master/highwayhashAVX2_amd64.s, what i wanted an opinion on was if converting this file to PPC (a pure assembly implemention) will be a faster  version as compared to using the .c/.h VSX files in this repo? @jan-wassenberg

**Comment by jan-wassenberg** [comment]
Hi, it's an interesting question. I find that clang translates x86 intrinsics quite well, such that assembly isn't a big win. Not sure how the situation is on POWER, I haven't looked at the assembly there.
