### ISSUE TITLE
Alignment warning when compiling with GCC7 on aarch64

### ISSUE THREAD

**Issue by zorrohahaha** [google/highwayhash#75]
g++ -c -I. -std=c++11 -Wall -O3 -fPIC -pthread highwayhash/vector_test_portable.cc -o obj/vector_test_portable.o
In file included from ./highwayhash/arch_specific.h:39:0,
                 from ./highwayhash/vector_test_target.h:23,
                 from ./highwayhash/vector_test_target.cc:18,
                 from highwayhash/vector_test_portable.cc:19:
./highwayhash/vector_test_target.cc: In function ‘void highwayhash::Portable::{anonymous}::NotifyIfUnequal(highwayhash::Portable::{anonymous}::V<T>&, T, size_t, highwayhash::HHNotify)’:
./highwayhash/compiler_specific.h:52:46: warning: requested alignment 32 is larger than 16 [-Wattributes]
 #define HH_ALIGNAS(multiple) alignas(multiple)  // C++11
                                              ^
./highwayhash/vector_test_target.cc:53:20: note: in expansion of macro ‘HH_ALIGNAS’
   T lanes[V<T>::N] HH_ALIGNAS(32);
                    ^~~~~~~~~~
./highwayhash/vector_test_target.cc: In function ‘void highwayhash::Portable::{anonymous}::TestLoadStore(highwayhash::HHNotify)’:
./highwayhash/compiler_specific.h:52:46: warning: requested alignment 32 is larger than 16 [-Wattributes]

**Comment by zorrohahaha** [comment]
When using GCC 4.8.5, there will be no warnings. (I haven't try the performance yet)

**Comment by jan-wassenberg** [comment]
Thanks for mentioning. I believe no action is needed here, overalignment is reasonable and apparently GCC 4.8.5 does not warn?
