### ISSUE TITLE
Failed to build on arm64

### ISSUE THREAD

**Issue by cdluminate** [google/highwayhash#83]
Buildlog: https://buildd.debian.org/status/fetch.php?pkg=highwayhash&arch=arm64&ver=0%7Egit20190222.276dd7b-1&stamp=1550977085&raw=0

Version: 0~git20190222.276dd7b (current master)

**Comment by kshmelev** [comment]
I have the same issue when cross-compiling HighwayHash to arm64. My log is very much alike to the one from the previous message. The causing error seems to be:

`make HH_AARCH64=1`
.....
`./highwayhash/hh_neon.h:227:76: error: no matching function for call to 'highwayhash::NEON::V128<unsigned int>::ShiftRightInsert(highwayhash::NEON::V2x64U&, long unsigned int)'`

The versions before the commit https://github.com/google/highwayhash/commit/ff5f27d785bda44e1ce0572b7f44943984ced61a work just fine.
