### ISSUE TITLE
SipHash performs badly on short msgs (< 100 bytes). And missing le64toh swap on key?

### ISSUE THREAD

**Issue by operamint** [google/highwayhash#86]
Hi,

1) I was recently comparing my old implementation of SipHash with this, and noticed it is much faster on shorter messages. My code is "straigth forward" pure portable C++ (< 150 lines)  without any macro, intrinsics or other trickery. Uses class Hash with ctor, update and finalize.
```
                     avg msg length  hwh::SipHash  my siphash    comp. opt.  speedup
VS 2017 (15.9.15)    10 (1-20)           8.8s          4.6s        -Ox         1.91x 
g++ 5.1.0 (TDM)      10 (1-20)           6.6s          4.2s        -O3         1.57x 
                   
VS 2017 (15.9.15)    25 (1-50)          27.2s         18.9s        -Ox         1.44x 
g++ 5.1.0 (TDM)      25 (1-50)          21.2s         15.6s        -O3         1.36x 
```
With increasingly longer messages, hwh::SipHash catches up with mine, but does not surpass it.  I tried with a few other compiler opt. args, but didn't see any difference. Tested on an  i7-8700 and i5-6600K with similar results.

FYI, since this is a widely use implementation and short messages is an important use case for many.

2) It appears you dont call host_from_le64() on the input key, as you do on the input message, but I haven't reviewed all the code to know for sure..

**Comment by jan-wassenberg** [comment]
Interesting result, thank you for sharing this.
It is difficult to draw conclusions from something like the sum of many runs. Would you like to integrate your code into the benchmark.cc? If it is indeed faster there, and you're willing to share your code, we could open-source it here.

2: the input key is given as an integer. Byte order only arises when loaded from bytes, as we do for the input message.

**Comment by operamint** [comment]
I would gladly share the code - I'll integrate into benchmark.cc. In the meantime, here are some more numbers: Note that my hashsip<2,4> optimizes great on both compilers, but the <1,3> instantiation doesn't optimize with Visual Studio 2017. Weird.
```
g++ -std=c++14 -O3 -mavx2 

 input len        hwh::SipHash  siphash::hash<2,4>   speedup    hwh::HighwayHash   speedup
         8               9.69s               6.17s     1.57x               6.83s     0.90x
        31               3.63s               2.64s     1.37x               1.78s     1.48x
        32               3.53s               2.85s     1.24x               1.37s     2.07x
        63               2.66s               2.19s     1.22x               0.98s     2.23x
        64               2.64s               2.29s     1.15x               0.83s     2.77x
      1024               1.81s               1.79s     1.01x               0.33s     5.38x
   1048576               1.76s               1.75s     1.00x               0.30s     5.80x

 input len      hwh::SipHash13  siphash::hash<1,3>   speedup
         8               7.07s               3.85s     1.84x
        31               2.64s               1.66s     1.60x
        32               2.28s               1.69s     1.35x
        63               1.64s               1.28s     1.28x
        64               1.55s               1.33s     1.16x
      1024               1.02s               1.01s     1.01x
   1048576               0.98s               0.98s     1.00x

cl -nologo -EHsc -std:c++14 -O2 -arch:AVX2

 input len        hwh::SipHash  siphash::hash<2,4>   speedup    hwh::HighwayHash   speedup
         8              11.77s               6.80s     1.73x               6.49s     1.05x
        31               3.89s               2.85s     1.36x               3.15s     0.90x
        32               4.11s               3.06s     1.34x               1.29s     2.37x
        63               2.86s               2.33s     1.23x               1.66s     1.41x
        64               2.98s               2.45s     1.22x               0.79s     3.09x
      1024               1.94s               1.86s     1.04x               0.33s     5.72x
   1048576               1.85s               1.83s     1.01x               0.29s     6.21x

 input len      hwh::SipHash13  siphash::hash<1,3>   speedup
         8               9.04s              14.26s     0.63x
        31               2.78s               4.24s     0.65x
        32               2.75s               4.24s     0.65x
        63               1.77s               2.54s     0.70x
        64               1.81s               2.54s     0.71x
      1024               1.02s               1.10s     0.92x
   1048576               0.96s               0.99s     0.96x
```
And extracts from the code that produced it:
```
    const double N = 5000000000.0;
    std::vector<int> input_lengths { 8, 31, 32, 63, 64, 1024, 1024 * 1024 };
    std::vector<uint16_t> data(input_lengths.back());
    for (uint16_t& m: data) m = rand();
    const uint16_t* in = data.data();
    
    cout << setprecision(2) << fixed;
    // SipHash 2-4
    cout << endl << setw(10) << "input len" << setw(20) << "hwh::SipHash"
         << setw(20) << "siphash::hash" << setw(10) << "speedup"
         << setw(20) << "hwh::HighwayHash" << setw(10) << "speedup" << endl ;
    for (int len: input_lengths) {
        size_t n = size_t(N / len);
        
        start = std::clock();
        for (auto i = 0; i < n; ++i) {
            sum_a += highwayhash::SipHash(key, (const char*) in, len);
        }
        time_a = (std::clock() - start) / (double) CLOCKS_PER_SEC;
        cout << setw(10) << len << setw(19) << time_a << "s";
        
        start = std::clock();
        for (auto i = 0; i < n; ++i) {
            sum_b += siphash::hash(key, in, len);
        }
        time_b = (std::clock() - start) / (double) CLOCKS_PER_SEC;
        cout << setw(19) << time_b << "s" << setw(9) << (time_a / time_b) << "x";
        
        highwayhash::HHResult64 result;  // or HHResult128 or HHResult256
        start = std::clock();
        for (auto i = 0; i < n; ++i) {
            highwayhash::HHStateT<HH_TARGET> state(key);
            highwayhash::HighwayHashT(&state, (const char*) in, len, &result);
            sum_c += result;
        }
        time_c = (std::clock() - start) / (double) CLOCKS_PER_SEC;
        cout << setw(19) << time_c << "s" << setw(9) << (time_b / time_c) << "x" << endl;
    }

```

**Comment by operamint** [comment]
Hi Jan, I have forked the project, if you're interested.

1. Added freewayhash::SipHash.  "_A freeway is a "controlled-access" highway — also known as an express highway — that's designed exclusively for high-speed vehicular traffic._". As from above table, it is approx.  2x - 1.2x faster for 7 - 63 bytes input lengths.
2. Integrated into benchmark.cc, but I find my own benchmarks show better differentiation: Larger differences on short inputs. On the flip side, your HighwayHash seems more like 6x faster than SipHash on long inputs, rather than your claimed 5x.  Maybe your benchmarking framework has some overhead that flattens the results a bit?
3. I also included a "no-branch" (no if), simpler freewayhash::v2::SipHash that requires multiples of 8 bytes in Update(), where you put the remaining in Finalize().  But technically, as it contains a conditional loop it is not branch free?

**Comment by jan-wassenberg** [comment]
Hi, thanks for integrating and testing! I didn't see the benchmark.cc results in your commit/readme - can you share those?

> I find my own benchmarks show better differentiation: Larger differences on short inputs
> Maybe your benchmarking framework has some overhead that flattens the results a bit?

Yes, this is by design. A long loop will lead to near-perfect icache and branch prediction, whereas our benchmark deliberately interferes with this by randomizing the input lengths.
