### ISSUE TITLE
Installs an unstripped binary lib/libhighwayhash.so

### ISSUE THREAD

**Issue by yurivict** [google/highwayhash#88]
```
Warning: 'lib/libhighwayhash.so' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
```

**Comment by jan-wassenberg** [comment]
@yurivict Thanks for suggesting this, would this be sufficient?

```
post-install:
	${STRIP_CMD} $(DESTDIR)/$(LIBDIR)/libhighwayhash.so

.PHONY: clean distclean all install post-install
```

**Comment by yurivict** [comment]
> Thanks for suggesting this, would this be sufficient?

I think so.

**Comment by jan-wassenberg** [comment]
@yurivict I finally merged the github version with our internal version (two-way sync was unfortunately not set up). Just added this and will push shortly.
