### ISSUE TITLE
Problem with Python 3 bindings

### ISSUE THREAD

**Issue by kaxap** [google/highwayhash#93]
There is a problem with https://github.com/kpdemetriou/highwayhash-cffi mentioned in the README.md of this project: 

it sometimes generates arbitrary hashes given the same input due to usage of deallocated memory region. I have submitted the  [issue](https://github.com/kpdemetriou/highwayhash-cffi/issues/1) and a [pull request](https://github.com/kpdemetriou/highwayhash-cffi/pull/2) fixing the issue over a month ago, but the author (@kpdemetriou) is not responding.

The issue is probably needs to be mentioned in the readme since it can cause a lot of grief to unsuspecting library users.

**Comment by jan-wassenberg** [comment]
Ouch, thanks for spreading the word to save others grief.

How about this text?
```
> **_NOTE:_**  For highwayhash-cffi, please note an [issue](https://github.com/kpdemetriou/highwayhash-cffi/issues/1)
has been reported ([merge request](https://github.com/kpdemetriou/highwayhash-cffi/pull/2)).

```

**Comment by kaxap** [comment]
That will do. Thanks!

**Comment by jan-wassenberg** [comment]
Thanks for having a look, we'll get it pushed to Github soon.

**Comment by kpdemetriou** [comment]
Hi all, I'm the author of the Python bindings in question. This is a quick heads-up that this issue has been rectified as of version 0.1.6.

**Comment by jan-wassenberg** [comment]
@kpdemetriou 
Hi Phil, good news, thanks for letting us know! FYI we're removing the text added above, or please let us know if you'd like something else mentioned instead.
