### ISSUE TITLE
The tricky __SSE4_1__ macro under Visual Studio

### ISSUE THREAD

**Issue by andrewevstyukhin** [google/highwayhash#96]
The target selection preprocessor's directive at
https://github.com/google/highwayhash/blob/7d165f0f7853f37d6b989e862c8859693ed02d32/highwayhash/arch_specific.h#L93
fails to use SSE4.1 in AVX builds under Visual Studio 2019. HH_TARGET_NAME equals to Portable.

A proposed modification in the expression works better:
`#elif defined(__SSE4_1__) || defined(__AVX__)`

Visual Studio defines SIMD macroses starting from `__AVX__`
https://stackoverflow.com/questions/18563978/detect-the-availability-of-sse-sse2-instruction-set-in-visual-studio
https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?redirectedfrom=MSDN&view=msvc-160

**Comment by jan-wassenberg** [comment]
Thank you!
